/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MongoBulkExecutorJava;

import org.junit.Test;
import java.util.ArrayList;
import java.util.UUID;

import org.bson.Document;

public class MongoBulkExecutorTests {
	@Test
	public void testOrderedBatch() throws Exception {
		MongoBulkExecutor classUnderTest = new MongoBulkExecutor();
		classUnderTest.bulkExecute(this.getRandomDocuments(10000), true, true);
		classUnderTest.PrintMetrics();
	}

	@Test
	public void testUnOrderedBatch() throws Exception {
		MongoBulkExecutor classUnderTest = new MongoBulkExecutor();
		classUnderTest.bulkExecute(this.getRandomDocuments(10000), false, true);
		classUnderTest.PrintMetrics();
	}

	private ArrayList<Document> getRandomDocuments(int batchSize) {
		ArrayList<Document> rv = new ArrayList<Document>();

		for (int i = 0; i < batchSize; i++) {
			rv.add(new Document().append("a", 1).append("id", UUID.randomUUID().toString()));
		}

		return rv;
	}
}
